language: go
sudo: false

go:
  # - 1.4
  # - 1.5
  # - 1.6
  # - 1.7
  # - 1.8.x
  - 1.9.x
  # - tip

# matrix:
#   allow_failures:
#     - go: 1.3

install:
  - go list -f '{{range .Imports}}{{.}} {{end}}' ./... | xargs go get -v
  - go list -f '{{range .TestImports}}{{.}} {{end}}' ./... | xargs go get -v

script:
  - go test ./...
  - go vet ./...
